[package]
name = "rloris"
version = "0.3.0"
authors = ["SilverWingedSeraph <lfstindall@gmail.com>"]

[dependencies]
log = "0.3"
env_logger = "0.4.0"
rustc-serialize = "0.3"
docopt = "0.7"
openssl = "0.9"